select count(w_id) as warehouse from warehouse;
select count(d_w_id) as district from district;
select count(c_w_id) as customer from customer;
select count(h_c_id) as history from history;
select count(no_w_id) as new_orders from new_orders;
select count(o_w_id) as orders from orders;
select count(ol_w_id) as order_line from order_line;
select count(i_id) as item from item;
select count(s_w_id) as stock from stock;
